# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
      uses: appleboy/ssh-action@v0.1.4
      with:
        password: ${{secrets.SSH_PASSWORD}}
        host: ${{secrets.HOST}}
        username: ${{secrets.USER_NAME}}
        port: ${{secrets.SSH_PORT}}
        script: |
          cd /home/docky/tiremanagementWebService
          docker-compose down
          cd tiremanagement-vue
          git pull
          npm install
          npm run build
          cd ./..
          docker-compose up -d
          
        
